### ISSUE TITLE
EOFError on new install

### ISSUE THREAD

**Issue by emschwar** [suvajitgupta/Tasks#6]
Following all instructions exactly, I started up my server for the first time. I logged in as SA, and clicked the "new task" button at the bottom of the screen. I then clicked on the "New Task" label, and typed "A renamed task", and hit Enter. I did nothing else; a few seconds later, I saw this error on my sc-server console:

EOFError: end of file reached
    /usr/local/lib/ruby/1.8/net/protocol.rb:135:in `sysread'
    /usr/local/lib/ruby/1.8/net/protocol.rb:135:in`rbuf_fill'
    /usr/local/lib/ruby/1.8/timeout.rb:62:in `timeout'
    /usr/local/lib/ruby/1.8/timeout.rb:93:in`timeout'
    /usr/local/lib/ruby/1.8/net/protocol.rb:134:in `rbuf_fill'
    /usr/local/lib/ruby/1.8/net/protocol.rb:116:in`readuntil'
    /usr/local/lib/ruby/1.8/net/protocol.rb:126:in `readline'
    /usr/local/lib/ruby/1.8/net/http.rb:2020:in`read_status_line'
    /usr/local/lib/ruby/1.8/net/http.rb:2009:in `read_new'
    /usr/local/lib/ruby/1.8/net/http.rb:1050:in`request'
    /home/emschwar/src/github/abbot/lib/sproutcore/rack/proxy.rb:78:in `handle_proxy'
    /usr/local/lib/ruby/1.8/net/http.rb:543:in`start'
    /usr/local/lib/ruby/1.8/net/http.rb:440:in `start'
    /home/emschwar/src/github/abbot/lib/sproutcore/rack/proxy.rb:69:in`handle_proxy'
    /home/emschwar/src/github/abbot/lib/sproutcore/rack/proxy.rb:25:in `call'
    /home/emschwar/src/github/abbot/lib/sproutcore/rack/proxy.rb:23:in`each'
    /home/emschwar/src/github/abbot/lib/sproutcore/rack/proxy.rb:23:in `call'
    /usr/local/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/cascade.rb:23:in`call'
    /usr/local/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/cascade.rb:22:in `each'
    /usr/local/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/cascade.rb:22:in`call'
    /usr/local/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/showexceptions.rb:24:in `call'
    /usr/local/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/recursive.rb:39:in`call'
    /usr/local/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/conditionalget.rb:23:in `call'
    /home/emschwar/src/github/abbot/lib/sproutcore/rack/service.rb:114:in`call'
    /usr/local/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/content_length.rb:13:in `call'
    /usr/local/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/chunked.rb:15:in`call'
    /usr/local/lib/ruby/gems/1.8/gems/thin-1.2.7/lib/thin/connection.rb:76:in `pre_process'
    /usr/local/lib/ruby/gems/1.8/gems/thin-1.2.7/lib/thin/connection.rb:74:in`catch'
    /usr/local/lib/ruby/gems/1.8/gems/thin-1.2.7/lib/thin/connection.rb:74:in `pre_process'
    /usr/local/lib/ruby/gems/1.8/gems/thin-1.2.7/lib/thin/connection.rb:57:in`process'
    /usr/local/lib/ruby/gems/1.8/gems/thin-1.2.7/lib/thin/connection.rb:42:in `receive_data'
    /usr/local/lib/ruby/gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run_machine'
    /usr/local/lib/ruby/gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    /usr/local/lib/ruby/gems/1.8/gems/thin-1.2.7/lib/thin/backends/base.rb:57:in`start'
    /usr/local/lib/ruby/gems/1.8/gems/thin-1.2.7/lib/thin/server.rb:156:in `start'
    /usr/local/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/handler/thin.rb:14:in`run'
    /home/emschwar/src/github/abbot/lib/sproutcore/rack/service.rb:97:in `start'
    /home/emschwar/src/github/abbot/lib/sproutcore/tools/server.rb:43:in`server'
    /usr/local/lib/ruby/gems/1.8/gems/thor-0.13.4/lib/thor/task.rb:33:in `send'
    /usr/local/lib/ruby/gems/1.8/gems/thor-0.13.4/lib/thor/task.rb:33:in`run'
    /usr/local/lib/ruby/gems/1.8/gems/thor-0.13.4/lib/thor/invocation.rb:109:in `invoke'
    /usr/local/lib/ruby/gems/1.8/gems/thor-0.13.4/lib/thor/invocation.rb:116:in`call'
    /usr/local/lib/ruby/gems/1.8/gems/thor-0.13.4/lib/thor/invocation.rb:116:in `invoke'
    /home/emschwar/src/github/abbot/lib/sproutcore/tools.rb:94:in`invoke'
    /usr/local/lib/ruby/gems/1.8/gems/thor-0.13.4/lib/thor.rb:137:in `start'
    /usr/local/lib/ruby/gems/1.8/gems/thor-0.13.4/lib/thor/base.rb:378:in`start'
    /usr/local/lib/ruby/gems/1.8/gems/thor-0.13.4/lib/thor.rb:124:in `start'
    /home/emschwar/src/github/abbot/lib/sproutcore/tools.rb:340:in`start'
    /home/emschwar/src/github/abbot/lib/sproutcore/tools.rb:29:in `invoke'
    ../abbot/bin/sc-server:11

**Comment by emschwar** [comment]
Duh, I forgot to include my javascript console output:

```
Uncaught SC.Error:sc34:Busy (-1)
(3) core.js:361Uncaught Error saving data: Save already in progress.
XHR finished loading: "http://localhost:4400/tasks-server/task?UUID=1&ATO=(null)&action=createTask&notify=true".
core_sources.js:183Error creating record [CoreTasks.Task]: SC.Error:sc1265:Internal Server Error (500)
core.js:695Uncaught Error saving data: Failed to save at least one task
```

**Comment by emschwar** [comment]
It turns out this is caused by using the latest abbot-- if I check out the REL-1.0.1046 tag in the abbot project, Tasks works great! If I use HEAD, then I see the behaviour above. I suggest the installation instructions, for now, be amended to ask the user to check out that specific tag in abbot.
